name: StaticAnalysis
on:
  workflow_call:

jobs:
  static-analysis:
    name: StaticAnalysis
    container: alpine:latest
    runs-on:
      - self-hosted
      - k8s-api
      - linux-amd64-m

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: StaticAnalysis
        id: build
        run: |
          echo "This is a StaticAnalysis stage"
